services:
  - type: web
    name: pamoja-backend
    env: python
    pythonVersion: "3.11.4"
    rootDir: api
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn index:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pamoja-db
          property: connectionString
      - key: DEMO_API_KEY
        sync: false
      - key: LIVE_API_KEY
        sync: false
      - key: API_PORT
        value: "10000"
      - key: API_HOST
        value: "0.0.0.0"

databases:
  - name: pamoja-db
    databaseName: pamoja
    user: pamoja
    plan: free
